ALTER TABLE `surveyQuestions` MODIFY COLUMN `createdAt` DATETIME NOT NULL DEFAULT NOW();
ALTER TABLE `surveyQuestions` MODIFY COLUMN `updatedAt` DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW();

INSERT INTO surveyQuestions (question, SurveyId) VALUES ("Your friend calls and says let's go grab a beer.  What do you do?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("How do you feel about snow, and winter in general?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("A horror movie comes on, what do you do?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("What's your stance on the great pineapple pizza debate?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("Are you an person whom is always on time?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("Country music, and go.", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("Is blue your favorite color?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("How do you feel about a hike for a date?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("How do you feel about Halloween?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("You have a week off, road trip?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("Would you drive/own a hybrid/electric car?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("Could you live in a tiny house?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("How close are you with your family?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("How do you feel about sandals?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("How do you feel about kids?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("In ten years do you see yourself in the same career/location?" , 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("Do you watch a lot of television?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("Are pets family?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("Are you a tattoo person?", 1);
INSERT INTO surveyQuestions (question, SurveyId) VALUES ("Do you like to read?", 1);
